base/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static


app_name = 'base'
urlpatterns = [
    path('', views.base, name='base'),
    path('position', views.position, name='position'),
    path('position/<slug:oti>/<slug:zoomie>', views.zoom, name='zoom'),
    path('quotes/', views.quotes, name='quotes'),
    path('new-shipment/', views.new_shipment, name='new-shipment'),
    path('load-countries', views.load_countries, name='counts'),
    path('billing', views.billing, name='billing'),
    path('login', views.login_request, name='login'),
    path('sign-up', views.register, name='sign-up'),
    path('logout', views.logout_request, name='logout'),
    path('tracking', views.tracking, name='tracking'),
    path('profile', views.profile, name='profile'),
    path('pfp', views.pfp, name='pfp'),
    path('mailer/', views.mailer, name='mailer'),
    path('create-new', views.create_new, name='create_new'),
    path("pinger/", views.pinger, name= "pinger"),
]


#if settings.DEBUG:
 #   urlpatterns +=  static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
  #  urlpatterns+= static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

chat/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'chat'

urlpatterns = [
    path('', views.chats, name='chat'),
    path('chat/support-ticket<str:c_id>', views.chat, name = 'single_chat'),
    path('chat/create-new-chat', views.create_new_ticket, name='new_chat'),
]


#if settings.DEBUG:
 #   urlpatterns +=  static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
  #  urlpatterns+= static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

shipper/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls')),
    path('chat/', include('chat.urls'))
]

#if settings.DEBUG:
 #   urlpatterns +=  static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
  #  urlpatterns+= static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

chat/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.

class ChatUser(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    has_new_message = models.BooleanField(default=False)
    pfp = models.ImageField(upload_to='pfp/', blank=True, null=True)

    def __str__(self):
        return self.user.username


class Support(models.Model):
    name = models.CharField(max_length=200)
    pfp = models.ImageField(upload_to='support_pfp')

    def __str__(self):
        return f'Customer support {self.name}'

class Chat(models.Model):
    chat_id = models.CharField(max_length=20)
    user = models.ForeignKey(ChatUser, on_delete=models.CASCADE)
    topic = models.CharField(max_length=200)
    support = models.ForeignKey(Support, on_delete=models.PROTECT)
    last_message = models.TextField(blank=True, null=True)
    last_edited = models.DateTimeField(auto_now=True)
    is_read = models.BooleanField(default=True)

    def __str__(self):
        return f'Chat between support and {self.user.user.username}'
    


class Message(models.Model):
    chat = models.ForeignKey(Chat, on_delete=models.CASCADE)
    text = models.TextField(blank=True, null=True)
    img = models.ImageField(upload_to='messages', blank=True, null=True)
    time = models.DateTimeField(auto_now_add=True)
    from_support = models.BooleanField(default=False)

chat/views.py
from django.shortcuts import render
from base.models import *
from .models import *
from django.http import HttpResponseRedirect, HttpResponseNotAllowed
from django.urls import reverse
import random



# Create your views here.

def chats(request):
    if request.user.is_authenticated:


        company_name = Company_name.objects.first()
        if request.user.is_superuser:
            sup_chats = Chat.objects.all()
            context = {'company_name': company_name, 'chats':sup_chats}
            return render(request, 'chat/chats.html', context)
        else:
            user, created = ChatUser.objects.get_or_create(user = request.user)
            cus_chats = Chat.objects.filter(user = user)
            user.has_new_message = False
            user.save()

            context = {'company_name': company_name, 'chats':cus_chats}
            return render(request, 'chat/chats.html', context)
    else:
        return HttpResponseRedirect(reverse('base:login'))

def chat(request, c_id):
    if request.user.is_authenticated:
        company_name = Company_name.objects.first()
        chat = Chat.objects.get(chat_id = c_id)
        messages = Message.objects.filter(chat = chat).order_by('time')

        def update_status():
            chat.user.has_new_message = True
            chat.user.save()
            chat.is_read = False
            chat.save()

            return None



        if request.method != 'POST':
            if request.user.is_superuser:
                pass
            else:
                chat.is_read = True
                chat.save()
            context = {'company_name': company_name, 'chat':chat, 'messages':messages}
            return render(request, 'chat/chat.html', context)
        else:
            if request.FILES:
                text = request.POST['text']
                text = text.strip()

                img = request.FILES['picture']

                if request.user.is_superuser:
                    Message.objects.create(chat = chat, text = text, img = img, from_support = True)
                    update_status()
                else:



                    Message.objects.create(chat = chat, text = text, img = img  )
                 

                return HttpResponseRedirect(reverse('chat:single_chat', args=[chat.chat_id,]))
            else:
                text = request.POST['text']
                text = text.strip()
                if text == "":
                    return HttpResponseRedirect(reverse('chat:single_chat', args=[chat.chat_id,]))
                if request.user.is_superuser:
                    Message.objects.create(chat = chat, text = text, from_support = True)
                    update_status()
                   
                else:

                    Message.objects.create(chat = chat, text = text)
                return HttpResponseRedirect(reverse('chat:single_chat', args=[chat.chat_id,]))

    else:
        return HttpResponseRedirect(reverse('base:login'))
    
def create_new_ticket(request):
    if request.user.is_authenticated: #checking that user is authenticated
        if request.method == 'POST': #checking method
            chat_user = ChatUser.objects.get(user = request.user)
            chat_id = random.randint(1111111,9999999999)
            topic = request.POST['topic']
            support = Support.objects.all().order_by('?').first()
            last_message = request.POST['des']

            new_chat = Chat.objects.create(chat_id = chat_id, user = chat_user, topic = topic, support = support, last_message = last_message)
            Message.objects.create(chat = new_chat, text = last_message)
            auto_reply = f'Hello {chat_user.user.first_name}, your message has been received and forwarded to the team in charge. We\'ll update you if any further action is required from you to process your issue ticket. Thanks for your understanding.'

            Message.objects.create(chat = new_chat, text = auto_reply, from_support = True)
            mail = request.POST['email']
            user_obj = User.objects.get(username = request.user.username)
            user_obj.email = mail
            user_obj.save()
            return HttpResponseRedirect(reverse('chat:single_chat', args=[chat_id]))
    else: #if user hasnt been authenticated, force them to.
        return HttpResponseRedirect(reverse('base:login'))
    

chat/templates/chat/chat.html
{% extends 'base/base.html' %}
{% load static %}
{% block content %}

<div class="box">
    <script>
        window.onload = function () {
            document.getElementById('blank').scrollIntoView(true)
        }
    </script>
    <p style="font-size: larger; text-align: center;">
        <b>
            {{chat.topic}}
        </b>
    </p>
    <div class="full-container">
        {% for m in messages %}
        <!--Checking before rendering-->
        {% if request.user.is_superuser %}

        <!--Render differnt view for support-->

        {% if m.from_support %}
   


        <div class="message-container-cus">

            <div class="cus_message message">
                {% if m.img %}
                <img src="{{m.img.url}}" alt="" class="m-image">
                {% endif %} <br>
                {{ m.text }} <br>
                <p class="time_sent"> {{m.time.time}} </p>
            </div>
            <div>
                <img class="support_pfp" src="{{chat.support.pfp.url}}" alt="">
            </div>
        </div>
        {% else %}
        <div class="message-container-support">

            <div>
                <img {% if chat.chatuser.pfp %} src="{{ chat.chatuser.pfp.url }}" {% else %} src="{% static 'images/blank.png' %}" {% endif %} alt="" class="support_pfp">
            </div> 
            <div class="sup_message message">
                {% if m.img %}
                <img src="{{m.img.url}}" alt="" class="m-image">
                {% endif %} <br>
                {{ m.text }} <br>
                <p class="time_sent">
                    {{m.time.time}}
                </p>
            </div>
        </div>

        {% endif %}





        {% else %}
        {% if m.from_support %}
        <div class="message-container-support">

            <div>
                <img src="{{chat.support.pfp.url}}" alt="" class="support_pfp">
            </div>
            <div class="sup_message message">
                {% if m.img %}
                <img src="{{m.img.url}}" alt="" class="m-image">
                {% endif %} <br>
                {{ m.text }} <br>
                <p class="time_sent">
                    {{m.time.time}}
                </p>
            </div>
        </div>

        {% else %}
        <div class="message-container-cus">

            <div class="cus_message message">
                {% if m.img %}
                <img src="{{m.img.url}}" alt="" class="m-image">
                {% endif %} <br>
                {{ m.text }} <br>
                <p class="time_sent"> {{m.time.time}} </p>
            </div>
            <div>
                <img class="support_pfp" {% if request.user.chatuser.pfp %} src="{{ request.user.chatuser.pfp.url }}" {%else %} src="{% static 'images/blank.png' %}" {% endif %} alt="">
            </div>
        </div>

        {% endif %}

        {% endif %}
        {% endfor %}
    </div>
    <div id="blank">

    </div>

    <form action="{% url 'chat:single_chat' chat.chat_id %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div id="message-form">

   

            <div>
                <input type="text" class="form-control" placeholder="Start typing..." name="text" id="text-input">
            </div>

            <div>
                <label for="picture">
                    <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="#007BFF"
                        class="bi bi-camera-fill" viewBox="0 0 16 16">
                        <path d="M10.5 8.5a2.5 2.5 0 1 1-5 0 2.5 2.5 0 0 1 5 0" />
                        <path
                            d="M2 4a2 2 0 0 0-2 2v6a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V6a2 2 0 0 0-2-2h-1.172a2 2 0 0 1-1.414-.586l-.828-.828A2 2 0 0 0 9.172 2H6.828a2 2 0 0 0-1.414.586l-.828.828A2 2 0 0 1 3.172 4zm.5 2a.5.5 0 1 1 0-1 .5.5 0 0 1 0 1m9 2.5a3.5 3.5 0 1 1-7 0 3.5 3.5 0 0 1 7 0" />
                    </svg>
                    <div id="display_val">

                    </div>

                </label>
                <input type="file" id="picture" class="form-control" placeholder="Attach picture" hidden name="picture">
            </div>

            <div>

                <label for="submit-btn">
                    <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="#007BFF"
                        class="bi bi-send-fill" viewBox="0 0 16 16">
                        <path
                            d="M15.964.686a.5.5 0 0 0-.65-.65L.767 5.855H.766l-.452.18a.5.5 0 0 0-.082.887l.41.26.001.002 4.995 3.178 3.178 4.995.002.002.26.41a.5.5 0 0 0 .886-.083zm-1.833 1.89L6.637 10.07l-.215-.338a.5.5 0 0 0-.154-.154l-.338-.215 7.494-7.494 1.178-.471z" />
                    </svg>
                </label>
                <input type="submit" id="submit-btn" value="" hidden>
            </div>


        </div>
    </form>
</div>
{% endblock %}

chat/templates/chat/chats.html
{% extends 'base/base.html' %}
{% load static %}
{% block content %}

{% if request.user.is_superuser %}
<div>
<div>
    Welcome, admin {{ request.user.username }}
</div>

<div class="chats">
    {% for c in chats %}
    <!--Single chat-->
    <a href="{% url 'chat:single_chat' c.chat_id %}" class="chat-link">
    <div class="chat">
        <div>
        <img class="support_pfp" src="{{c.support.pfp.url}}" alt="">
    </div>

        <div style="display: block;">
            <b style="text-transform: capitalize;">{{c.user.user.username}}</b> <br>
            <span> {{ c.last_message|slice:50 }}...</span>
        </div>

        <div class="time">
            {% if c.is_read %}
            <p style="padding: 2px; background-color: white; height: 20px; width: 20px; border-radius: 50%; white-space: nowrap;">

            {% else %}
            <p style="padding: 2px; background-color: green; height: 20px; width: 20px; border-radius: 50%; white-space: nowrap;">
                {% endif %} <br>
                {{c.last_edited.time}}
            </p>
            
        </div>
    </div>
</a>
    <!--Single chat ends here-->
    {% endfor %}


    
</div>
</div>
{% else %}
<!--Head-->
<div class="support-head">
    <div class="header">
<div style="font-size: x-large; clear: set-warp;">
    <b style="text-transform: uppercase; ">{{company_name.name}}</b> help center

</div>
<div class="btn btn-outline-secondary">
    <span class="my set-warp">
        <a href="{% url 'base:profile' %}" class="car-link">
    My {{company_name.name}}
</a>
</span>
</div>
    </div>
</div>

<!--COntact div-->

<div class="contact-us-head unset-warp">
    <h1 class="rm_scrollbar unset-warp">
        Contact Us
    </h1>
    <p>
        Question, bug reports, feedback and more...we at {{company_name.name}} are always at your service.
    </p>
</div>



<!--Form field-->
<form action="{% url 'chat:new_chat' %}" method="post">
    {% csrf_token %}
<div class="form unset-warp">
    <div class="fields unset-warp">
        <label for="topic">
            Enter topic of conversation:
        </label>
        <input type="text" placeholder="Topic" id="topic" name="topic" class="form-control" required>
        <br>
        <label for="des">Describe your issue:</label>
        <textarea required name="des" id="des" cols="30" rows="10" class="form-control" placeholder="Tell us more about what you need help with..."></textarea> <br>
        <label for="email">Enter your email address:</label>
        {% if request.user.email %}
        <input type="email" name="email" id="email" value="{{request.user.email}}" class="form-control">
        {% else %}
        <input type="email" name="email" id="email" placeholder="Email address" class="form-control">
        
        <small>We will only use this to update you on progress with your issue. We at {{company_name.name}} corporation pride ourselves in privacy and would never sell your data.</small>
        {% endif %} <br>
        <input type="submit" class="form-control btn-outline-primary" value="Get Help">
    </div>
</div>
</form>

<br> <br>
<h2 class="rm_scrollbar"> <b>
    Open issues
</b>
</h2>
{% if chats %}
<div class="chats">
    {% for c in chats %}
    <!--Single chat-->
    <a href="{% url 'chat:single_chat' c.chat_id %}" class="chat-link">
    <div class="chat">
        <div>
        <img class="support_pfp" src="{{c.support.pfp.url}}" alt="">
    </div>

        <div style="display: block;">
            <b style="text-transform: capitalize;">{{c.support.name}}</b> <br>
            <span> {{ c.last_message|slice:50 }}...</span>
        </div>

        <div class="time">
            {% if c.is_read %}
            <p style="padding: 2px; background-color: white; height: 20px; width: 20px; border-radius: 50%; white-space: nowrap !important; overflow-x: unset !important; text-overflow: unset !important;">

            {% else %}
            <p style="padding: 2px; background-color: green; height: 20px; width: 20px; border-radius: 50%; white-space: nowrap !important; overflow-x: unset !important; text-overflow: unset !important;">
                {% endif %} <br>
               {{c.last_edited.time}}
            </p>
            
        </div>
    </div>
</a>
    <!--Single chat ends here-->
    {% endfor %}


    
</div>
{% else %}
<div class="chats">
<p style="font-weight: 800; font-size: 30px;">No unresolved issues to display.</p>
</div>
{% endif %}


<br> <br> <br>
{% endif %}
{% endblock %}

chat/templates/chat/page.html
{% load static %}

<img src="c.user.chatuser.pfp.url" alt="None" width="600px">