base/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static


app_name = 'base'
urlpatterns = [
    path('', views.base, name='base'),
    path('position', views.position, name='position'),
    path('position/<slug:oti>/<slug:zoomie>', views.zoom, name='zoom'),
    path('quotes/', views.quotes, name='quotes'),
    path('new-shipment/', views.new_shipment, name='new-shipment'),
    path('load-countries', views.load_countries, name='counts'),
    path('billing', views.billing, name='billing'),
    path('login', views.login_request, name='login'),
    path('sign-up', views.register, name='sign-up'),
    path('logout', views.logout_request, name='logout'),
    path('tracking', views.tracking, name='tracking'),
    path('profile', views.profile, name='profile'),
    path('pfp', views.pfp, name='pfp'),
    path('mailer/', views.mailer, name='mailer'),
    path('create-new', views.create_new, name='create_new'),
    path("pinger/", views.pinger, name= "pinger"),
]


#if settings.DEBUG:
 #   urlpatterns +=  static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
  #  urlpatterns+= static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

chat/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'chat'

urlpatterns = [
    path('', views.chats, name='chat'),
    path('chat/support-ticket<str:c_id>', views.chat, name = 'single_chat'),
    path('chat/create-new-chat', views.create_new_ticket, name='new_chat'),
]


#if settings.DEBUG:
 #   urlpatterns +=  static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
  #  urlpatterns+= static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

shipper/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls')),
    path('chat/', include('chat.urls'))
]

#if settings.DEBUG:
 #   urlpatterns +=  static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
  #  urlpatterns+= static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

base/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Countries(models.Model):
    name = models.CharField(max_length=20)
    
    def __str__(self):
        return self.name


class Quote(models.Model):
    ship_from = models.CharField(max_length=50)
    ship_to = models.CharField(max_length=50)
    weight = models.IntegerField()
    length = models.IntegerField()
    width = models.IntegerField()
    height = models.IntegerField()
    email = models.EmailField()

    def __str__(self):
        return f'Quotes from {self.ship_from} to {self.ship_to} for {self.email}'
    
class Company_name(models.Model):
    name = models.CharField(max_length=20)

    def __str__(self):
        return f'{self.name}'

class Shipper(models.Model):
    first_name = models.CharField(max_length=20)
    last_name = models.CharField(max_length=20)
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    phone_number = models.CharField(max_length=20, null=True, blank=True)
    pfp = models.ImageField(upload_to='pfp/', blank=True, null=True)
    location =models.CharField(max_length=30)


    def __str__(self):
        return f'{self.first_name} {self.last_name}'
    
class Receiver(models.Model):
    first_name = models.CharField(max_length=20)
    last_name = models.CharField(max_length=20)
    address_line = models.TextField()
    address_line2 = models.TextField(blank=True, null=True)
    city_and_zip_code = models.TextField()
    phone_number = models.CharField(max_length=20)
    email = models.EmailField()

    def __str__(self):
        return f'Receiver {self.first_name} {self.last_name}'
    
ORDER_STATUS = [
   ('PE', 'Pending'),
    ('PU', 'Picked up'),
    ('OH', 'On Hold'),
    ('OD', 'Out for delivery'),
    ('IT', 'In-Transit'),
    ('EN', 'Enroute'),
    ('CA', 'Cancelled'),
    ('DE', 'Delivered'),
    ('RE', 'Returned'),
]    

"""Class to track model"""
class Order(models.Model):

    tracking_id = models.CharField(max_length=10)
    screen_width = models.IntegerField(blank=True, null=True)
    latitude = models.FloatField()
    longitude = models.FloatField()
    zoom = models.FloatField(default=0.0)
    current_position = models.CharField(max_length=40)
    expected_date = models.CharField(max_length=20)
    carrier = models.CharField(max_length=20)
    ship_date = models.DateField()
    shipping_service = models.CharField(max_length=20)
    shipped_from = models.CharField(max_length=30)
    shipping_to = models.CharField(max_length=30)
    shipping_cost = models.FloatField()
    shipper = models.ForeignKey(Shipper, on_delete=models.CASCADE)
    receiver = models.ForeignKey(Receiver, on_delete=models.CASCADE)
    on_hold = models.BooleanField(default=False)
    comment = models.TextField()
    qty = models.CharField(max_length=10)
    piece_type = models.CharField(max_length=20)
    description = models.TextField()
    length = models.CharField(max_length=10)
    width = models.CharField(max_length=10)
    height = models.CharField(max_length=10)
    weight = models.CharField(max_length=10)
    status =  models.CharField(max_length=2, choices=ORDER_STATUS, default='PE')



    def __str__(self):
        return self.tracking_id

    def get_status(self):
        return dict(ORDER_STATUS).get(self.status, 'Unknown')
    
class MailError(models.Model):
    text = models.TextField()
    mail = models.EmailField()

    def __str__(self):
        return self.mail
    
class TempUser(models.Model):
    user_email = models.EmailField()
    username = models.CharField(max_length=20)
    otp = models.CharField(max_length=7)
    first_name = models.CharField(max_length=20)
    last_name = models.CharField(max_length=20)
    phone_number = models.CharField(max_length=20)
    password = models.CharField(max_length=30)
    

    def __str__(self):
        return f'{self.otp} for {self.username}'

base/views.py
from django.shortcuts import render
from .models import *
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth import login, logout, authenticate
from django.db import IntegrityError
from django.core.mail import send_mail

import random , time , requests
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

# Create your views here.

def base(request):
    company_name = Company_name.objects.first()
    context = {'company_name':company_name}
    return render(request, 'base/home.html', context)

def position(request):
    company_name = Company_name.objects.first()
    if request.method == 'POST':
        try:
            tracking_id = request.POST['tracking_id']
            order = Order.objects.get(tracking_id = tracking_id)
            screen_width = request.POST['width']
            
            if int(screen_width) > 600:
                screen_width= 600

            order.screen_width = screen_width
            order.zoom = 1.0
            order.save()
            scr_width = str(order.screen_width)
            
            context={'order':order, 'scr_width':scr_width,'company_name':company_name}
            return render(request, 'base/position.html', context)
        except(KeyError, Order.DoesNotExist):
            err = 'We couldn\'t find the tracking information for this parcel. Please ensure the tracking ID is correct and hasn\'t already been fulfilled.'
            note = 'Please note that the tracking ID is case-sensitive. "OrDer1" is not the same as "oRdER1"'
            context={'company_name':company_name, 'err': err, 'note':note}
            return render(request, 'base/home.html', context)
    context={'order':order, 'scr_width':scr_width, 'company_name':company_name}
    return render(request, 'base/position.html', context)

def zoom(request, oti, zoomie):
    company_name = Company_name.objects.first()
    order = Order.objects.get(tracking_id = oti)
    if zoomie == "plus" and order.zoom<20:
        order.zoom = order.zoom + 0.5
        order.save()
        context = {'order':order, 'scr_width':order.screen_width, 'company_name':company_name}
        return render(request, 'base/position.html', context)
  
   
    if zoomie =="minus" and order.zoom >1:
        order.zoom= order.zoom - 0.5
        order.save()
        context = {'order':order, 'scr_width':order.screen_width, 'company_name':company_name}
        return render(request, 'base/position.html', context)
    else:
        err="MINIMUM/MAXIMUM ZOOM ACHIEVED"
        context = {'order':order, 'scr_width':order.screen_width, 'err':err, 'company_name':company_name}
        return render(request, 'base/position.html', context)
    

def quotes(request):
    company_name = Company_name.objects.first()
    if request.method == 'POST':
        ship_from = request.POST['from']
        ship_to = request.POST['to']
        weight = request.POST['weight']
        length = request.POST['length']
        width = request.POST['width']
        height = request.POST['height']
        email = request.POST['email']
        new_quote = Quote.objects.create(ship_from=ship_from,
                                          ship_to = ship_to, weight=weight,
                                          length=length, width=width,
                                            height= height, email=email)

        msg = 'Quote requested. We would get back to you as soon as possible.'
        context = {'msg':msg, 'company_name':company_name}
        return render(request, 'base/quotes.html', context)
    countries = Countries.objects.all()
    context = {'company_name':company_name, 'countries':countries}
    return render(request, 'base/quotes.html', context)

def new_shipment(request):
    company_name = Company_name.objects.first()
    countries = Countries.objects.all()
    context = {'company_name': company_name, 'countries':countries}
    return render(request, 'base/new-shipment.html', context)

def load_countries(request):
    countries = [
    "Argentina",
    "Australia",
    "Austria",
    "Belgium",
    "Brazil",
    "Canada",
    "China Mainland",
    "Colombia",
    "Costa Rica",
    "Czech Republic",
    "Denmark",
    "Dominican Republic",
    "Finland",
    "France",
    "Germany",
    "Greece",
    "Hong Kong SAR, China",
    "Hungary",
    "India",
    "Indonesia",
    "Ireland, Republic of",
    "Italy",
    "Japan",
    "Korea, South",
    "Luxembourg",
    "Macau SAR, China",
    "Malaysia",
    "Mexico",
    "Netherlands",
    "New Zealand",
    "Norway",
    "Philippines",
    "Poland",
    "Portugal",
    "Puerto Rico",
    "Romania",
    "Singapore",
    "South Africa",
    "Spain",
    "Sweden",
    "Switzerland",
    "Taiwan, China",
    "Thailand",
    "United Kingdom",
    "United States",
    "Vietnam"]
    for count in countries:
        c = Countries.objects.create(name = count)
        c.save()
    print('Countries loaded')


def billing(request):
    company_name = Company_name.objects.first()
    context  ={'company_name': company_name}
    return render(request, 'base/billing.html', context)

def login_request(request):
    company_name = Company_name.objects.first()

    if request.method == 'POST':
    
        if '@' in request.POST['username']:
            try:
                possible_user = User.objects.get(email = request.POST['username'])
            except(KeyError, User.DoesNotExist):
                try:

                    possible_user = User.objects.get(username = request.POST['username'])
                except(KeyError, User.DoesNotExist):
                    msg = 'Invalid username or password'
                    context = {'company_name': company_name, 'msg': msg}
                    return render(request, 'base/login.html', context)
            user = authenticate(request, username = possible_user.username, password = request.POST['password'])
            print(possible_user.username)
            print(request.POST['password'])
            if user is not None:

                login(request, user)
                return HttpResponseRedirect(reverse('base:base'))
            else:
                msg = 'Invalid username or password.'
                context = {'company_name': company_name, 'msg': msg}
                return render(request, 'base/login.html', context)

        else:

            user = authenticate(request, username = request.POST['username'], password = request.POST['password'])
            if user is not None:

                login(request, user)
                return HttpResponseRedirect(reverse('base:base'))
            else:
                msg = 'Invalid username or password.'
                context = {'company_name': company_name, 'msg': msg}
                return render(request, 'base/login.html', context)



    else:
        context  ={'company_name': company_name}
        return render(request, 'base/login.html', context)

def register(request):
    company_name = Company_name.objects.first()
    if request.method == 'POST':

        first_name = request.POST['first']
        last_name = request.POST['last']
        email = request.POST['email']
        password1 = request.POST['password1']
        password2 = request.POST['password2']
        phone_number = request.POST['number']
        username = request.POST['username']

        if password1 == password2:
            try:
                existing = User.objects.get(email = email)
                msg = f"A user with this email {email} already exists. Try logging in instead."
                context = {'msg':msg, 'company_name':company_name}
                return render(request, 'base/login.html', context)
            except User.DoesNotExist:
                otp = random.randint(100000, 999999)
                message = f"Hello {username}, this is your one time registration password. {otp} Use it to complete your email verification and activate your {company_name.name} account. If you did not initiate this action, simply ignore. DO NOT FORWARD THIS CODE TO ANYBODY."

                try:

                    send_mail(
                        "Welcome to Dosojin",
                        message,
                        "hello@dosojincargos.online",
                        [email],
                        fail_silently=False,
                    )
                except Exception as e:
                    MailError.objects.create(text = e, mail = email)
                TempUser.objects.create(username = username, user_email = email, otp = otp, first_name = first_name, last_name = last_name, phone_number = phone_number, password = password1)

                context ={'company_name': company_name, 'email':email, 'username':username}

                return render(request, 'base/confirmation.html', context)


        else:
            company_name = Company_name.objects.first()
            context = {'msg': 'Passwords do not match. Check and try again.', 'company_name': company_name}
            return render(request, 'base/signup.html', context)

    else:
        company_name = Company_name.objects.first()
        context  ={'company_name': company_name}
        return render(request, 'base/signup.html', context)
def create_new(request):
    company_name = Company_name.objects.first()
    if request.method == 'POST':

        email = request.POST['email']
        otp = request.POST['otp']
        temp_user = TempUser.objects.filter(user_email = email).last()
        if otp == temp_user.otp:
            

    
            
            try:
                temps = TempUser.objects.filter(user_email = email)
                for t in temps:
                    t.delete()
                

                new_user = User.objects.create_user(first_name = temp_user.first_name, last_name = temp_user.last_name, email = temp_user.user_email, username = temp_user.username, password= temp_user.password)
                new_user.save()

base/templates/base/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css"
        integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    <link rel="stylesheet" href="{% static 'css/chat.css' %}">
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct"
        crossorigin="anonymous"></script>
    <title>{{company_name.name}} Corporation</title>
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
        <a class="navbar-brand" href="{% url 'base:base' %}"><span id="logo">{{company_name.name|upper}}</span><svg
                xmlns="http://www.w3.org/2000/svg" width="55" height="55" fill="currentColor" class="bi bi-water"
                viewBox="0 0 16 16">
                <path
                    d="M.036 3.314a.5.5 0 0 1 .65-.278l1.757.703a1.5 1.5 0 0 0 1.114 0l1.014-.406a2.5 2.5 0 0 1 1.857 0l1.015.406a1.5 1.5 0 0 0 1.114 0l1.014-.406a2.5 2.5 0 0 1 1.857 0l1.015.406a1.5 1.5 0 0 0 1.114 0l1.757-.703a.5.5 0 1 1 .372.928l-1.758.703a2.5 2.5 0 0 1-1.857 0l-1.014-.406a1.5 1.5 0 0 0-1.114 0l-1.015.406a2.5 2.5 0 0 1-1.857 0l-1.014-.406a1.5 1.5 0 0 0-1.114 0l-1.015.406a2.5 2.5 0 0 1-1.857 0L.314 3.964a.5.5 0 0 1-.278-.65m0 3a.5.5 0 0 1 .65-.278l1.757.703a1.5 1.5 0 0 0 1.114 0l1.014-.406a2.5 2.5 0 0 1 1.857 0l1.015.406a1.5 1.5 0 0 0 1.114 0l1.014-.406a2.5 2.5 0 0 1 1.857 0l1.015.406a1.5 1.5 0 0 0 1.114 0l1.757-.703a.5.5 0 1 1 .372.928l-1.758.703a2.5 2.5 0 0 1-1.857 0l-1.014-.406a1.5 1.5 0 0 0-1.114 0l-1.015.406a2.5 2.5 0 0 1-1.857 0l-1.014-.406a1.5 1.5 0 0 0-1.114 0l-1.015.406a2.5 2.5 0 0 1-1.857 0L.314 6.964a.5.5 0 0 1-.278-.65m0 3a.5.5 0 0 1 .65-.278l1.757.703a1.5 1.5 0 0 0 1.114 0l1.014-.406a2.5 2.5 0 0 1 1.857 0l1.015.406a1.5 1.5 0 0 0 1.114 0l1.014-.406a2.5 2.5 0 0 1 1.857 0l1.015.406a1.5 1.5 0 0 0 1.114 0l1.757-.703a.5.5 0 1 1 .372.928l-1.758.703a2.5 2.5 0 0 1-1.857 0l-1.014-.406a1.5 1.5 0 0 0-1.114 0l-1.015.406a2.5 2.5 0 0 1-1.857 0l-1.014-.406a1.5 1.5 0 0 0-1.114 0l-1.015.406a2.5 2.5 0 0 1-1.857 0L.314 9.964a.5.5 0 0 1-.278-.65m0 3a.5.5 0 0 1 .65-.278l1.757.703a1.5 1.5 0 0 0 1.114 0l1.014-.406a2.5 2.5 0 0 1 1.857 0l1.015.406a1.5 1.5 0 0 0 1.114 0l1.014-.406a2.5 2.5 0 0 1 1.857 0l1.015.406a1.5 1.5 0 0 0 1.114 0l1.757-.703a.5.5 0 1 1 .372.928l-1.758.703a2.5 2.5 0 0 1-1.857 0l-1.014-.406a1.5 1.5 0 0 0-1.114 0l-1.015.406a2.5 2.5 0 0 1-1.857 0l-1.014-.406a1.5 1.5 0 0 0-1.114 0l-1.015.406a2.5 2.5 0 0 1-1.857 0l-1.757-.703a.5.5 0 0 1-.278-.65" />
            </svg>&nbsp;</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'base:new-shipment' %}">Shipping<span
                            class="sr-only">(current)</span></a>
                </li>







                <li class="nav-item">
                    <a class="nav-link" href="{% url 'base:tracking' %}">Tracking</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="{% url 'base:billing' %}">Produtcs & Services</a>
                </li>


                <li class="nav-item">
                    {% if request.user.is_authenticated %}
                    <a href="{% url 'base:profile' %}" class="nav-link">
                        My {{company_name.name}}
                    </a>
                    {% else %}
                    <a href="{% url 'base:sign-up' %}" class="nav-link">
                        Open an Account
                        <small style="font-size: xx-small;">Get 75% off business deliveries</small>
                    </a>
                    {% endif %}


                </li>
            </ul>
            {% if user.is_authenticated %}
            <a class="btn btn-outline-secondary my-2 my-sm-0" href="{% url 'base:profile' %}">
                {{request.user.username}}
            </a>
            {% else %}
            <a class="btn btn-outline-secondary my-2 my-sm-0" href="{% url 'base:login' %}">
                Log In
            </a>
            {% endif %}
            {% if request.user.is_authenticated %}
            <a class="btn btn-outline-danger my-2 my-sm-0" href="{% url 'base:logout' %}">
                Log Out
            </a>
            {% endif %}
        </div>
    </nav>


    {% if request.user.is_authenticated %}

        {% if request.user.is_superuser %}
            <a href="{% url 'chat:chat' %}">
                <div class="chat-box-container">
                    <div class="chat-box">
                        <svg xmlns="http://www.w3.org/2000/svg" width="50" height="50" fill="currentColor" class="bi bi-chat-fill" viewBox="0 0 16 16">
                            <path d="M8 15c4.418 0 8-3.134 8-7s-3.582-7-8-7-8 3.134-8 7c0 1.76.743 3.37 1.97 4.6-.097 1.016-.417 2.13-.771 2.966-.079.186.074.394.273.362 2.256-.37 3.597-.938 4.18-1.234A9 9 0 0 0 8 15"/>
                          </svg>
                    </div>
                    You're authenticated as a superuser. Please, note
                </div>
            </a>
            You're authenticated as a superuser. Please, note



        {% else %}
            {% if request.user.chatuser.has_new_message %}
     

                <a href="{% url 'chat:chat' %}">
                    <div class="chat-box-container">
                        <div class="chat-box">
                            <svg xmlns="http://www.w3.org/2000/svg" width="50" height="50" fill="#007BFF" class="bi bi-chat new"
                                viewBox="0 0 16 16">
                                <path
                                    d="M2.678 11.894a1 1 0 0 1 .287.801 11 11 0 0 1-.398 2c1.395-.323 2.247-.697 2.634-.893a1 1 0 0 1 .71-.074A8 8 0 0 0 8 14c3.996 0 7-2.807 7-6s-3.004-6-7-6-7 2.808-7 6c0 1.468.617 2.83 1.678 3.894m-.493 3.905a22 22 0 0 1-.713.129c-.2.032-.352-.176-.273-.362a10 10 0 0 0 .244-.637l.003-.01c.248-.72.45-1.548.524-2.319C.743 11.37 0 9.76 0 8c0-3.866 3.582-7 8-7s8 3.134 8 7-3.582 7-8 7a9 9 0 0 1-2.347-.306c-.52.263-1.639.742-3.468 1.105" />
                            </svg>
                        </div>
                    </div>
                </a>

                <style>
                    .new{
                        animation: new_message;
                        animation-fill-mode: forwards;
                        animation-iteration-count: infinite;
                        animation-duration: 3s;
                        animation-timing-function: ease-in-out;
                            }
                 
                    @keyframes new_message {
                        0% {width: 50px;
                        height: 50px;}
                        50% {width: 100px;
                        height: 100px;}
                        100% {width: 50px; height: 50px;}
                        
                    }
                </style>

            {% else %}

                    <a href="{% url 'chat:chat' %}">
                        <div class="chat-box-container">
                            <div class="chat-box">
                                <svg xmlns="http://www.w3.org/2000/svg" width="50" height="50" fill="#007BFF" class="bi bi-chat"
                                    viewBox="0 0 16 16">
                                    <path
                                        d="M2.678 11.894a1 1 0 0 1 .287.801 11 11 0 0 1-.398 2c1.395-.323 2.247-.697 2.634-.893a1 1 0 0 1 .71-.074A8 8 0 0 0 8 14c3.996 0 7-2.807 7-6s-3.004-6-7-6-7 2.808-7 6c0 1.468.617 2.83 1.678 3.894m-.493 3.905a22 22 0 0 1-.713.129c-.2.032-.352-.176-.273-.362a10 10 0 0 0 .244-.637l.003-.01c.248-.72.45-1.548.524-2.319C.743 11.37 0 9.76 0 8c0-3.866 3.582-7 8-7s8 3.134 8 7-3.582 7-8 7a9 9 0 0 1-2.347-.306c-.52.263-1.639.742-3.468 1.105" />
                                </svg>
                            </div>
                        </div>
                    </a>
            {% endif %}
        {% endif %}

    {% else %}
    <a href="{% url 'chat:chat' %}">
        <div class="chat-box-container">
            <div class="chat-box">
                <svg xmlns="http://www.w3.org/2000/svg" width="50" height="50" fill="#007BFF" class="bi bi-chat"
                    viewBox="0 0 16 16">
                    <path
                        d="M2.678 11.894a1 1 0 0 1 .287.801 11 11 0 0 1-.398 2c1.395-.323 2.247-.697 2.634-.893a1 1 0 0 1 .71-.074A8 8 0 0 0 8 14c3.996 0 7-2.807 7-6s-3.004-6-7-6-7 2.808-7 6c0 1.468.617 2.83 1.678 3.894m-.493 3.905a22 22 0 0 1-.713.129c-.2.032-.352-.176-.273-.362a10 10 0 0 0 .244-.637l.003-.01c.248-.72.45-1.548.524-2.319C.743 11.37 0 9.76 0 8c0-3.866 3.582-7 8-7s8 3.134 8 7-3.582 7-8 7a9 9 0 0 1-2.347-.306c-.52.263-1.639.742-3.468 1.105" />
                </svg>
            </div>
        </div>
    </a>
    {% endif %}


    <div class="box">
        {% block content %}
        {% endblock %}
    </div>

    <div class="translate" id="google_translate_element"></div>

    <script type="text/javascript">
        function googleTranslateElementInit() {
            new google.translate.TranslateElement({ pageLanguage: 'en' }, 'google_translate_element');
        }
    </script>

    <script type="text/javascript"
        src="//translate.google.com/translate_a/element.js?cb=googleTranslateElementInit"></script>



    <div class="explore">
        <h1 class="explore_head rm_scrollbar">
            Uncover {{company_name.name}}
        </h1>

        <div class="explore_col" style="padding-left: 50px;">
            <h4 class="explore_header rm_scrollbar">About Us</h4>
            <ul>
                <li>
                    <a class="bottom-links" href="">
                        About {{company_name.name}}
                    </a>
                </li>
                <li>
                    <a class="bottom-links" href="{% url 'base:new-shipment' %}">
                        Shipping
                    </a>
                </li>

                <li>
                    <a class="bottom-links" href="{% url 'base:quotes' %}">
                        Request a quote
                    </a>
                </li>

                <li>
                    <a class="bottom-links" href="{% url 'base:tracking' %}">
                        Tracking
                    </a>
                </li>
                <li>
                    <a class="bottom-links" href="{% url 'base:billing' %}">
                        Products and Services
                    </a>
                </li>

                <li>
                    {% if request.user.is_authenticated %}

                    <a class="bottom-links" href="{% url 'base:profile' %}">
                        My {{company_name.name}}
                    </a>
                    {% else %}
                    <a class="bottom-links" href="{% url 'base:login' %}">Get more with {{company_name.name}}</a>
                    {% endif %}

                </li>
            </ul>
        </div>
    </div>


</body>



</html>

base/templates/base/template.html
{% extends 'base/base.html' %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% block content %}
    {% endblock %}
</body>
</html>